name: Publish release

on:
  release:
    types: [published]

jobs:
  build-and-publish-pypi:
    name: Builds and publishes release to PyPI
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"

      - name: Install workflow dependencies
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          poetry version --no-interaction "${version}"

      - name: Build package
        run: poetry build --no-interaction

      - name: Publish to PyPi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "${PYPI_TOKEN}"
          poetry publish --no-interaction
